name: Code Climate

on:
  pull_request:
    branches:
      - main

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '14'

      - name: Install dependencies
        run: npm install

      - name: Run tests with coverage
        run: npm test -- --coverage

  codeclimate:
    runs-on: ubuntu-latest

    needs: test

    steps:
      - name: Upload coverage to Code Climate
        uses: codeclimate/github-action@v1.0.4
        with:
          debug: true
          coverage-reports: coverage/lcov.info
        env:
          CC_TEST_REPORTER_ID: ${{ secrets.CC_TEST_REPORTER_ID }}
