name: Generate JSDoc Documentation

on:
  push:

jobs:
  publish:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v1

      - name: Build JSDoc
        uses: codevise/documentation-js-action@v1
        with:
          input: .
          output: ./docs